name: ${APP_NAME}

services:
  # Development application service.
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ${APP_NAME}
    ports:
      - '3002:3000'
      - '5557:5555'
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    user: '1000:1000'
    networks:
      - web-apps
    restart: unless-stopped

    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
    name: ${APP_NAME}-postgres-data
  redis_data:
    name: ${APP_NAME}-redis-data

networks:
  web-apps:
    external: true
